version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kittygram_user -d kittygram"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: qprym/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: qprym/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: qprym/kittygram_gateway:latest
    ports:
      - "9000:80"
    volumes:
      - static:/staticfiles
      - media:/app/media
    depends_on:
      - backend
      - frontend