volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: qprym/kittygram_backend
    env_file: .env
    volumes:
      - media:/app/media/
      - static:/backend_static/static
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: qprym/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: qprym/kittygram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/static
    depends_on:
      - backend
      - frontend