version: '3'

volumes:
  pg_data:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kittygram_user -d kittygram"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: qprym00/kittygram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/app/collected_static/
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: qprym00/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static/

  gateway:
    image: qprym00/kittygram_gateway:latest
    ports:
      - "9000:80"
    volumes:
      - static_volume:/staticfiles/
      - media:/app/media
    depends_on:
      - backend
      - frontend